//-KS- = KOOPA SHELL
//-RB- = ROCKET BOOTS
//-VN- = VANETAL

// É È Û Î À 

COURSE_ACTS(COURSE_BOB, _(" 1 BASSIN BOUILLANT"), //étoiles trompeuses
       _("ÉTOILES TROMPEUSES"),     _("PIÈCES ROUGES SUR GEYSERS") , _("EN HAUT DE LA CHUTE DE LAVE"),
       _("DÉBARRASSAGE EXPRESS")  , _("LE DÉFI DES ANNEAUX"),        _("100 PIÈCES BRÛLANTES"),        _("LE ROI DES VOYOUS"))

COURSE_ACTS(COURSE_WF, _(" 2 FERME FLOTTANTE"),
       _("ARRACHER LES MAUVAISES HERBES") , _("TOUT EN HAUT DE LA FERME") , _("TOUT EN BAS DU SILO"),
       _("LA BERCEUSE DU COCHON"),          _("ANNEAUX À CHEVAL")         , _("100 PIÈCES ARROSÉES"), _("ARRIVER A BON PORC"))

COURSE_ACTS(COURSE_JRB, _(" 3 SAVANE SAUVAGE"),
       _("LES 5 PIÈCES YOSHI")    , _("LE SOMMET DE LA MONTAGNE") , _("LIBÉRER LE VILLAGE"),
       _("BALADE EN BLOC-SERPENT")  , _("PROPULSION DE PRÉCISION")     , _("100 PIÈCES PRÉHISTORIQUES"),_("LE POKEY ANCESTRAL"))

//courses are swaped!
COURSE_ACTS(COURSE_CCM, _(" 4 LE MARAUDEUR SPECTRAL"),
       _("HISSEZ LES VOILES !"),     _("8 PIÈCES ROUGES À LA MER") , _("LE SUPPLICE DES PLANCHES"),
       _("BLOC-SERPENT GLISSANT"), /*_("THE GOBLET OF SEA MEN")*/    _("LE CALICE DU CAPITAINE") ,  _("100 PIÈCES HANTÉES"), _("BATAILLE NAVALE"))

COURSE_ACTS(COURSE_BBH, _(" 5 VIRTUAPLEX"),
       _("DE TOIT EN TOIT") , _("GLISSADE SEPTIQUE") , _("BOÎTES ET BOUTONS"),
       _("COMBAT EN CAGE")  , _("VORTEX NUMÉRIQUE")  , _("100 PIÈCES PIXELLISÉES"), _("MONSIEUR LE DIRECTEUR"))

COURSE_ACTS(COURSE_HMC, _(" 6 CANYON COWBOY"),
       _("LA VALLÉE DES ROCHES")          , _("BILL-BALADE DANS LES AIRS") , _("LES PIÈCES ROUGES DU PROSPECTEUR"),
       _("CHAUD À LA CORDE DANS LA MINE") , _("LES BANDITS BAGARREURS")    , _("100 PIÈCES DÉSERTIQUES"),           _("COURSE-POURSUITE SUR LE TRAIN !"))

COURSE_ACTS(COURSE_LLL, _(" 7 RÉSIDENCE IMMENSE"),
       _("OPÉRATION FROMAGE")      , _("LES PIÈCES ROUGES DU SALON") , _("LES ANNEAUX DE LA CUISINE"),
       _("CHASSE AUX CHAUSSETTES") , _("AU FEU !")                   , _("100 PIÈCES MINIATURES"),     _("L'ASPIRA-PEUR"))

COURSE_ACTS(COURSE_SSL, _(" 8 RÉTROLAND"),
       _("PIÈCES ROUGES ET TUYAUX VERTS") , _("ASCENSION DU MONT BILLE BALLE") , _("THWOMPS ET CARAPACES"),
       _("GLISSE SUR GLACE"),               _("LA CLÉ DE PHANTO")             , _("100 PIÈCES ET 1-UP"),_("RETROWSER"))

COURSE_ACTS(COURSE_DDD, _(" 9 TOURS TWHOMP"),
       _("DUEL CONTRE LE ROI THWOMP") , _("LES ANNEAUX DU TOIT DES TOURS") , _("REMONTER LA FONTAINE DE LAVE"),
       _("COMBAT DE HAUTE VOLTIGE")   , _("BLOC-SERPENT REBELLE")          , _("100 PIÈCES EN PIERRE")        ,_("L'ATTAQUE DE LA REINE THWOMP"))

COURSE_ACTS(COURSE_SL, _(" 10 INDIGOPOLIS"),
       _("AU SOMMET DE LA VILLE") , _("PIÈCES ROUGES, ACIDE BLEU") , _("HEXAGONES INFERNAUX"),
       _("DÉDALE INVÉTAL")        , _("BOUÉE RISQUÉE")     , _("1100100 PIÈCES BINAIRES") ,_("LE SUPERQUIZ"))

COURSE_ACTS(COURSE_WDW, _("11 FUNESTE FESTELLA"),
       _("PETIT TOUR DE GRANDE ROUE")          , _("LA STATION DE TRAITEMENT")  , _("LES PIÈCES ROUGES DE LA GRAND-RUE") ,
       _("LE QUATUOR DES SOEURS")   , _("PARKOUR POUR ANNEAUX")      , _("100 PIÈCES URBAINES")               , _("ASCENSION DE LA CONSTRUCTION"))

COURSE_ACTS(COURSE_TTM, _("12 ÎLES ORCHESTRALES"),
       _("LA FALAISE DU RÉCIF") , _("SURF SUR TOITURE") , _("BRISER LES ORBES COSMIQUES"),
       _("LES PIÈCES ROSES DES ÎLES")          , _("LE SECRET DU MOULIN")  , _("100 PIÈCES DAMNÉES")        /*("100 COINS OF THE SOULS WHO PAID")*/ ,_("ÉRUPTION COSMIQUE"))

COURSE_ACTS(COURSE_THI, _("13 HAVRE ASSOURDI"),
       _("SUR LE PLUS HAUT DES TOITS") , _("PIÈCES ROSES EN PENTE")   , _("COURSE AUX GRAFFITIS"),
       _("L'ÉNIGME DE LA CABANE")         , _("GRAINE COSMIQUE EN CAGE") , _("100 PIÈCES CUBIQUES") , _("MORT AUX STATUES D'OR"))

COURSE_ACTS(COURSE_TTC, _("14 ULTIME EMPIRE"),
       _("SAUTS MURAUX SUR MURS PENCHÉS") , _("LES PIÈCES ROSES DU PARC")       , _("SUS À LA HAUTECANNE"),
       _("SUR LA MONTAGNE DE JAIS") , _("LE DERNIER REMPART") , _("100 PIÈCES REBELLES") ,_("LE GARDIEN DU TEMPLE"))

COURSE_ACTS(COURSE_RR, _("15 ÉPREUVES DE TERMINUS"),
       _("ÉPREUVE ROUGE")     , _("ÉPREUVE JAUNE") , _("ÉPREUVE VERTE"),
       _("ÉPREUVE CYAN") , _("ÉPREUVE BLEUE") , _("ÉPREUVE ROSE") , _("COEUR D'AGAMEMNON"))

SECRET_STAR(COURSE_BITDW, _("   POURSUITE À TOUTE VITESSE"))
SECRET_STAR(COURSE_BITFS, _("   DUEL AVEC LE PRÉSENTATEUR"))
SECRET_STAR(COURSE_BITS, _("   -"))
SECRET_STAR(COURSE_PSS, _("   ÉGOUTS DÉGOÛTANTS"))
SECRET_STAR(COURSE_COTMC, _("   -"))//metal cap
SECRET_STAR(COURSE_TOTWC, _("   -"))//wing cap
SECRET_STAR(COURSE_VCUTM, _("   -"))//vanish cap
SECRET_STAR(COURSE_WMOTR, _("   CITÉ PERDUE"))
SECRET_STAR(COURSE_SA, _("   USINE SECRÈTE"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   ÉTOILES SECRÈTES"))

EXTRA_TEXT(0, _("UNE ÉTOILE SECRÈTE !"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
